---
title: '`voice` vignette'
subtitle: 'version `r packageVersion("voice")`'
author: 'Filipe J. Zabala'
date: "`r format(Sys.time(), '%Y-%m-%d')`"
# date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{`voice` vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
ini0 <- Sys.time()
```

## 0. Installation
### 0.1 Minimal
```{r, message=FALSE, warning=FALSE, eval=FALSE}
# CRAN (stable)
install.packages('voice', dep = TRUE)

# Github (development)
devtools::install_github('filipezabala/voice')
```

### 0.2 Full
https://github.com/filipezabala/voice


## 1. Extract features
### 1.1 Get path to audio files
```{r, message=FALSE, warning=FALSE}
wavFiles <- list.files(system.file('extdata', package = 'wrassp'),
                       pattern <- glob2rx('*.wav'), full.names = TRUE)
```

### 1.2 Minimal usage
```{r, message=FALSE, warning=FALSE}
M <- voice::extract_features(wavFiles)
dplyr::glimpse(M)
```

## 2. Tag
### 2.1 Creating synthetic Extended data
```{r, message=FALSE, warning=FALSE}
E <- dplyr::tibble(subject_id = c(1,1,1,2,2,2,3,3,3), wav_path = wavFiles)
E
```

### 2.2 Tagging Extended data
```{r, message=FALSE, warning=FALSE}
voice::tag(E)
```

### 2.3 Tagging Canonical data
```{r, message=FALSE, warning=FALSE}
voice::tag(E, groupBy = 'subject_id')
```
